### ISSUE TITLE
Add to F-Droid

### ISSUE THREAD

**Issue by pizzamaker** [jorgegil96/All-NBA#31]
It would be handy to have this app distributed through F-Droid. Do you think that would be feasible?

**Comment by jorgegil96** [comment]
Hey @pizzamaker 
I'm actually not very familiar with F-droid but from a quick glance at the wiki I have a small concern about monetization in the platform.  
My current plans don't include it being a paid app, but I do think that ads might be necessary in the future to pay for server costs. From what I read paid apps are a nono in F-droid and it looks like ads would be hard to implement without proprietary software.

I'll look more into it next week and I'll try to figure out a way to make it work, I can reduce server calls by doing more stuff on the client side and removing some features, or maybe donations would be enough.

I might also not pursue this right now, since the app is still in alpha and nowhere near a stable release.

I'll look into it and update the thread.

**Comment by pizzamaker** [comment]
Thanks for considering it in any case :)

Paid apps and ads are not a problem as long as they're using free software. The trick is, as you mentioned, avoid proprietary software.
